services:
  article-service:
    build:
      target: dev
    environment:
      APP_ENV: dev
    volumes:
      - ./article-service:/app
      - /app/var

  article-service-consumer:
    build:
      target: dev
    environment:
      APP_ENV: dev
    volumes:
      - ./article-service:/app
      - /app/var

  frontend:
    build:
      target: dev
    environment:
      NODE_ENV: dev
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 100
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: 100
    volumes:
      - ./frontend:/app