# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    kafka.brokers: '%env(KAFKA_BROKERS)%'
    kafka.topic.keycloak: '%env(default:kafka.topic.keycloak.default:KAFKA_TOPIC_KEYCLOAK)%'
    kafka.topic.keycloak.default: 'keycloak-events'
    keycloak.realm.default: 'collector_realms'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Command\ConsumeKeycloakEventsCommand:
        arguments:
            $kafkaBrokers: '%kafka.brokers%'
            $kafkaTopic: '%kafka.topic.keycloak%'

    App\Command\SyncKeycloakUsersCommand:
        arguments:
            $keycloakUrl: '%env(KEYCLOAK_URL)%'
            $keycloakRealm: '%env(default:keycloak.realm.default:KEYCLOAK_REALM)%'
            $keycloakAdminUser: '%env(KEYCLOAK_ADMIN)%'
            $keycloakAdminPassword: '%env(KEYCLOAK_ADMIN_PASSWORD)%'
