apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: marketplace
data:
  VITE_KEYCLOAK_URL: "http://localhost:8080"
  VITE_KEYCLOAK_REALM: "collector_realms"
  VITE_KEYCLOAK_CLIENT_ID: "collector_front"
  VITE_API_URL: "http://localhost:8000"
